/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package ko.test

import ko.test.domain.*


fun main() {
    val ticket = Ticket(1000)
    val bag = Bag(10000, null, ticket)
    val office = TicketOffice(10000, mutableListOf(ticket))
    val audience = Audience(bag)
    val seller = TicketSeller(office)
    val theater = Theater(seller)

    println(theater)

    theater.enter(audience)

    println(theater)
}