/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package ko.test

import ko.test.adapter.`in`.SampleAdaptor
import ko.test.adapter.out.InMemoryAdaptor
import ko.test.application.BorrowBookService
import ko.test.domain.Book
import ko.test.domain.Person

fun main() {
    val jake = Person("Jake", emptyList())
    val book = Book("1", "The Hobbit", "J.R.R. Tolkien")
    val book2 = Book("2", "The Book", "The Author")

    val library = InMemoryAdaptor()
    library.addBook(book)
    library.addBook(book2)
    library.listBooks().forEach { println(it) }

    val service = BorrowBookService(library)

    SampleAdaptor(service).borrowBook(jake, book)

    library.listBooks().forEach { println(it) }
}